name: lottie_flutter
version: 0.1.0
description: Lottie widget and demo for Flutter.
authors:
  - Fabiomsr 
  - Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/lottie_flutter

dependencies:
  path_drawing: ^0.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  inflection: any
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/muzli.json
    - assets/empty_box.json
    - assets/happy_gift.json
    - assets/walkthrough.json
    - assets/emoji_shock.json
    - assets/preloader.json
    - assets/checked_done_.json
    - assets/favourite_app_icon.json
    - assets/motorcycle.json
    - assets/hamburger_arrow.json
    - assets/Indicators2.json

environment:
  sdk: ">=1.19.0"
  flutter: ">=0.3.6 <2.0.0"